# security config
server:
  port: 8081

#config some parameters
root:
  username: "lelandacm"
  password: "123456"

acme:
  remote-address: 192.168.1.1
  security:
    username: admin
    password: admin
    roles:
      - USER
      - ADMIN
my:
  secret: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  uuid: ${random.uuid}
  withIn10: ${random.int(10)}

  numberRange: ${random.int[1024,65535]}