# security config
server:
  port: 8081

#config some parameters
root:
  username: "lelandacm"
  password: "123456"

acme:
  remote-address: 192.168.1.1
  security:
    username: admin
    password: admin
    roles:
      - USER
      - ADMIN